export const sourceWeightByName: Record<string, number> = {
  TechCrunch: 0.05,
  Wired: 0.05,
  "The Verge": 0.05,
  "BusinessWorld Banking": 0.08,
  "BusinessMirror Business": 0.07,
  "Inquirer Business": 0.07,
  "Philstar Business": 0.06,
  "Manila Bulletin Business": 0.06,
  "Reuters Asia Banking": 0.07,
  "Nikkei Asia Business": 0.06,
  "The Business Times Banking": 0.05,
  "Jakarta Post Business": 0.04,
  "VNExpress Business": 0.04,
  "Bangko Sentral ng Pilipinas": 0.08,
  "Department of Finance": 0.05,
  "Development Bank of the Philippines": 0.03,
  "Asian Development Bank": 0.05,
  "Fitch Ratings Banks": 0.05,
  "Moody's Banking": 0.05,
  "S&P Global Banking": 0.05,
  "Bangko Sentral ng Pilipinas Property": 0.1,
  "Santos Knight Frank Market Reports": 0.09,
  "Department of Finance Property": 0.06,
  "BusinessWorld Property": 0.08,
  "BusinessMirror Property": 0.07,
  "Inquirer Business Property": 0.07,
  "Philippine Star Property": 0.06,
  "Malaya Business Property": 0.06,
  "Manila Bulletin Business Property": 0.06
};
