import type { Beat } from "../lib/types.js";

export type BeatRelevanceConfig = {
  core_ai_keywords: string[];
  ai_infra_keywords: string[];
  adjacent_tech_keywords: string[];
  applied_human_keywords: string[];
  keep_signal_keywords: {
    model_release: string[];
    developer_platform: string[];
    ai_infrastructure: string[];
    enterprise_rollout: string[];
    strategic_partnership: string[];
    policy_regulation: string[];
    licensing_copyright: string[];
    safety_governance: string[];
    strategic_finance: string[];
  };
  junk_keywords: string[];
  min_score: number;
};

export const relevanceConfigByBeat: Record<Beat, BeatRelevanceConfig> = {
  ai_tech: {
    core_ai_keywords: [
      "ai",
      "artificial intelligence",
      "machine learning",
      "generative ai",
      "genai",
      "model",
      "models",
      "llm",
      "llms",
      "large language model",
      "large language models",
      "language model",
      "language models",
      "gpt",
      "dall-e",
      "dalle",
      "clip",
      "whisper",
      "codex",
      "operator",
      "system card",
      "reasoning",
      "alignment",
      "benchmark",
      "eval",
      "evaluation",
      "model spec",
      "vision",
      "sora",
      "multimodal",
      "inference",
      "training",
      "fine-tuning",
      "fine tuning",
      "image generation",
      "text to image",
      "theorem proving",
      "reinforcement learning",
      "rl",
      "robotics",
      "embeddings",
      "curriculum learning",
      "neural network",
      "neural networks",
      "transformer",
      "transformers",
      "diffusion",
      "prompt injection",
      "policy gradient",
      "math word problems",
      "prompt",
      "prompts",
      "use case",
      "use-case",
      "business",
      "enterprise",
      "workflow",
      "productivity",
      "application",
      "applications",
      "customer service",
      "developer",
      "developers",
      "reasoning model",
      "agent",
      "agents",
      "agentic",
      "openai",
      "anthropic",
      "claude",
      "chatgpt",
      "gemini",
      "copilot"
    ],
    ai_infra_keywords: [
      "gpu",
      "gpus",
      "chip",
      "chips",
      "semiconductor",
      "cuda",
      "tpu",
      "inference chip",
      "data center",
      "datacenter",
      "cloud",
      "compute",
      "accelerator",
      "accelerated computing",
      "foundation model",
      "model serving",
      "ai factory",
      "robotics",
      "autonomous",
      "developer platform",
      "api",
      "infrastructure"
    ],
    adjacent_tech_keywords: [
      "antitrust",
      "regulation",
      "policy",
      "copyright",
      "safety",
      "security",
      "cybersecurity",
      "privacy",
      "platform",
      "app store",
      "search",
      "browser",
      "microsoft",
      "google",
      "meta",
      "amazon",
      "apple",
      "nvidia",
      "startup",
      "business software",
      "enterprise ai",
      "enterprise workflow",
      "developer tools",
      "enterprise software",
      "developer",
      "open source"
    ],
    applied_human_keywords: [
      "how to",
      "ways to",
      "using ai",
      "use ai",
      "everyday",
      "daily",
      "workflow",
      "automate",
      "automation",
      "productivity",
      "save time",
      "real world",
      "real-world",
      "small business",
      "freelancer",
      "student",
      "teacher",
      "marketing",
      "sales",
      "content",
      "customer service",
      "operations",
      "hiring",
      "training",
      "fun",
      "weird",
      "viral",
      "trend",
      "experiment",
      "challenge",
      "test",
      "people are using",
      "someone used ai to",
      "created using ai",
      "generated using ai",
      "understanding",
      "impact",
      "ethical"
    ],
    keep_signal_keywords: {
      model_release: [
        "introducing",
        "launch",
        "launches",
        "released",
        "release",
        "update",
        "now available",
        "system card",
        "model spec"
      ],
      developer_platform: [
        "api",
        "developer",
        "developers",
        "developer platform",
        "sdk",
        "platform",
        "devtools",
        "app server"
      ],
      ai_infrastructure: [
        "gpu",
        "chip",
        "chips",
        "compute",
        "cloud",
        "data center",
        "datacenter",
        "inference",
        "training",
        "semiconductor",
        "infrastructure"
      ],
      enterprise_rollout: [
        "deploy",
        "deployment",
        "rollout",
        "scale",
        "scaling",
        "enterprise",
        "for work",
        "business",
        "workforce"
      ],
      strategic_partnership: [
        "partner",
        "partners",
        "partnership",
        "collaborate",
        "collaboration",
        "joint statement",
        "agreement"
      ],
      policy_regulation: [
        "policy",
        "regulation",
        "regulatory",
        "court",
        "lawsuit",
        "litigation",
        "antitrust",
        "doj",
        "eu"
      ],
      licensing_copyright: [
        "license",
        "licenses",
        "licensing",
        "copyright",
        "publisher",
        "publishers",
        "news organizations",
        "content partnership"
      ],
      safety_governance: [
        "safety",
        "governance",
        "alignment",
        "risk",
        "trust",
        "security",
        "evaluation",
        "eval",
        "red team"
      ],
      strategic_finance: [
        "funding",
        "fundraise",
        "investment",
        "invests",
        "stake",
        "acquire",
        "acquisition",
        "credit facility"
      ]
    },
    junk_keywords: [
      "coupon",
      "promo code",
      "coupons",
      "deals",
      "discount",
      "sale",
      "price drop",
      "under $",
      "percent off",
      "off right now",
      "for the rest of today",
      "roundup",
      "gift guide",
      "buy now",
      "where to buy",
      "earbuds",
      "phone case",
      "apple watch bands",
      "outdoor pizza ovens",
      "accessories",
      "geforce now",
      "cloud gaming",
      "game on"
    ],
    min_score: 2
  },
  philippine_motoring: {
    core_ai_keywords: [
      "srp",
      "price",
      "prices",
      "pricing",
      "financing",
      "loan",
      "monthly",
      "downpayment",
      "affordable",
      "affordability",
      "ownership cost",
      "fuel price",
      "fuel prices",
      "gasoline",
      "diesel",
      "maintenance",
      "insurance",
      "registration",
      "lto",
      "dotr",
      "toll",
      "tolls",
      "traffic",
      "congestion",
      "diesel rollback",
      "gasoline rollback",
      "pump price",
      "oil price"
    ],
    ai_infra_keywords: [
      "ev",
      "evs",
      "electric vehicle",
      "electric vehicles",
      "hybrid",
      "electrified",
      "phev",
      "charging",
      "charger",
      "charging station",
      "battery",
      "range",
      "road",
      "roads",
      "expressway",
      "mobility",
      "transport infrastructure",
      "infrastructure",
      "rail",
      "public transport"
    ],
    adjacent_tech_keywords: [
      "suv",
      "pickup",
      "mpv",
      "sedan",
      "crossover",
      "commercial vehicle",
      "fleet",
      "sales",
      "vehicle sales",
      "car sales",
      "demand",
      "market share",
      "segment",
      "inventory",
      "backlog",
      "supply",
      "availability",
      "import",
      "tariff",
      "excise tax",
      "policy",
      "regulation",
      "enforcement",
      "emissions"
    ],
    applied_human_keywords: [
      "buyers",
      "owners",
      "drivers",
      "commuters",
      "families",
      "small business",
      "tnvs",
      "fleet",
      "operators",
      "dealers",
      "dealership",
      "after-sales",
      "service",
      "warranty",
      "resale",
      "total cost of ownership",
      "operating cost",
      "cost of ownership"
    ],
    keep_signal_keywords: {
      model_release: [
        "launch",
        "launched",
        "unveils",
        "introduces",
        "now available",
        "arrives",
        "philippines",
        "philippine",
        "srp",
        "price",
        "financing",
        "hybrid",
        "ev",
        "evs",
        "electrified",
        "segment"
      ],
      developer_platform: [
        "dealer",
        "dealership",
        "booking",
        "online reservation",
        "app",
        "service network",
        "charging network"
      ],
      ai_infrastructure: [
        "charging",
        "charger",
        "charging station",
        "road",
        "roads",
        "toll",
        "expressway",
        "infrastructure",
        "congestion",
        "parking"
      ],
      enterprise_rollout: [
        "fleet",
        "commercial vehicle",
        "operators",
        "tnvs",
        "logistics",
        "delivery",
        "transport"
      ],
      strategic_partnership: [
        "partner",
        "partnership",
        "distributor",
        "dealer",
        "agreement",
        "joint venture"
      ],
      policy_regulation: [
        "lto",
        "dotr",
        "ltfrb",
        "mmda",
        "regulation",
        "policy",
        "enforcement",
        "registration",
        "plates",
        "license",
        "emissions",
        "excise tax"
      ],
      licensing_copyright: [
        "registration",
        "license",
        "franchise",
        "permit",
        "compliance"
      ],
      safety_governance: [
        "safety",
        "recall",
        "crash",
        "defect",
        "inspection",
        "enforcement"
      ],
      strategic_finance: [
        "investment",
        "funding",
        "plant",
        "production",
        "capacity",
        "supply",
        "inventory",
        "backlog"
      ]
    },
    junk_keywords: [
      "coupon",
      "promo code",
      "discount code",
      "die-cast",
      "scale model",
      "wallpaper",
      "render",
      "spy shot",
      "teaser",
      "concept only",
      "motorsport",
      "racing game",
      "f1",
      "formula 1",
      "bike accessories",
      "car accessories",
      "car care tips",
      "how to wash",
      "listicle"
    ],
    min_score: 3
  },
  ph_sea_banking: {
    core_ai_keywords: [
      "bank",
      "banks",
      "banking",
      "lender",
      "lenders",
      "loan",
      "loans",
      "lending",
      "credit",
      "borrowers",
      "consumer loans",
      "corporate loans",
      "loan growth",
      "credit growth",
      "deposit",
      "deposits",
      "casa",
      "time deposit",
      "deposit growth",
      "liquidity",
      "funding",
      "capital",
      "funding cost",
      "net interest margin",
      "margin",
      "npl",
      "non-performing loan",
      "nonperforming loan",
      "provision",
      "provisions",
      "provisioning",
      "risk",
      "exposure",
      "restructuring"
    ],
    ai_infra_keywords: [
      "bsp",
      "bangko sentral",
      "central bank",
      "dof",
      "reserve requirement",
      "rrr",
      "capital adequacy",
      "capital requirement",
      "regulation",
      "regulatory",
      "supervision",
      "compliance",
      "monetary board",
      "adb",
      "fitch",
      "moody",
      "s&p",
      "rating",
      "ratings"
    ],
    adjacent_tech_keywords: [
      "digital bank",
      "digital banking",
      "fintech",
      "e-wallet",
      "payments",
      "cost structure",
      "fund migration",
      "deposit competition",
      "competitive pressure",
      "southeast asia",
      "asean",
      "regional",
      "indonesia",
      "vietnam",
      "singapore",
      "thailand",
      "malaysia"
    ],
    applied_human_keywords: [
      "tighten",
      "tightening",
      "loosen",
      "loosening",
      "rise",
      "rising",
      "fall",
      "falling",
      "slowdown",
      "expand",
      "expansion",
      "shift",
      "shifting",
      "migration",
      "preserve",
      "preserving",
      "reprice",
      "repricing",
      "higher yield",
      "funding pressure",
      "credit appetite",
      "risk appetite"
    ],
    keep_signal_keywords: {
      model_release: [
        "loan growth",
        "credit growth",
        "lending",
        "consumer loans",
        "corporate loans",
        "borrowers"
      ],
      developer_platform: [
        "deposit",
        "deposits",
        "casa",
        "time deposit",
        "deposit growth",
        "fund migration"
      ],
      ai_infrastructure: [
        "liquidity",
        "funding",
        "reserve requirement",
        "capital adequacy",
        "funding cost",
        "margin"
      ],
      enterprise_rollout: [
        "npl",
        "non-performing",
        "provision",
        "provisioning",
        "credit loss",
        "stress",
        "restructuring"
      ],
      strategic_partnership: [
        "digital bank",
        "digital banking",
        "fintech",
        "fund migration",
        "cost structure",
        "deposit competition"
      ],
      policy_regulation: [
        "bsp",
        "bangko sentral",
        "central bank",
        "dof",
        "regulation",
        "regulatory",
        "reserve requirement",
        "monetary board"
      ],
      licensing_copyright: [
        "capital requirement",
        "capital adequacy",
        "compliance",
        "supervision",
        "license"
      ],
      safety_governance: [
        "risk",
        "npl",
        "non-performing",
        "provision",
        "stress",
        "exposure",
        "rating"
      ],
      strategic_finance: [
        "funding",
        "capital raise",
        "bond issue",
        "notes",
        "wholesale funding",
        "cost of funds"
      ]
    },
    junk_keywords: [
      "award",
      "awards",
      "named best",
      "branch opening",
      "opens branch",
      "appoints",
      "appointed",
      "promo",
      "cashback",
      "credit card promo",
      "best credit card",
      "best bank account",
      "savings tips",
      "how to save",
      "stock pick",
      "target price",
      "buy rating",
      "sell rating",
      "dividend",
      "share price"
    ],
    min_score: 5
  },
  ph_sea_energy: {
    core_ai_keywords: [
      "energy",
      "power",
      "electricity",
      "generation",
      "capacity",
      "supply",
      "fuel",
      "oil",
      "lng",
      "coal",
      "gas"
    ],
    ai_infra_keywords: [
      "department of energy",
      "doe",
      "energy regulatory commission",
      "erc",
      "grid",
      "transmission",
      "ngcp",
      "national grid",
      "meralco",
      "wesm"
    ],
    adjacent_tech_keywords: [
      "pump price",
      "fuel price",
      "electricity rate",
      "power rate",
      "tariff",
      "subsidy",
      "asean",
      "southeast asia"
    ],
    applied_human_keywords: [],
    keep_signal_keywords: {
      model_release: [],
      developer_platform: [],
      ai_infrastructure: [],
      enterprise_rollout: [],
      strategic_partnership: [],
      policy_regulation: [],
      licensing_copyright: [],
      safety_governance: [],
      strategic_finance: []
    },
    junk_keywords: [
      "award",
      "awards",
      "csr",
      "appoints",
      "appointed"
    ],
    min_score: 5
  },
  property_real_estate: {
    core_ai_keywords: [
      "affordability",
      "affordable housing",
      "housing credit",
      "housing lending",
      "housing loan",
      "housing loans",
      "home financing",
      "green home financing",
      "green housing lending",
      "home loan",
      "home loans",
      "mortgage",
      "mortgages",
      "mortgage lending",
      "real estate lending",
      "residential real estate lending",
      "property financing",
      "interest rate",
      "interest rates",
      "bank lending",
      "take-up",
      "take up",
      "absorption",
      "occupancy",
      "vacancy",
      "unsold inventory",
      "inventory",
      "oversupply",
      "slower demand",
      "weaker demand",
      "price pressure",
      "rental pressure",
      "defaults",
      "distress",
      "distressed",
      "project delays",
      "purchasing power"
    ],
    ai_infra_keywords: [
      "bsp",
      "bangko sentral",
      "psa",
      "dhsud",
      "neda",
      "dof",
      "property index",
      "residential real estate price index",
      "building permits",
      "construction",
      "pipeline",
      "housing backlog",
      "zoning",
      "land use",
      "tax",
      "incentives",
      "capital charge",
      "capital charges",
      "capital requirement",
      "capital requirements",
      "risk weight",
      "risk weights",
      "financing incentive",
      "financing incentives"
    ],
    adjacent_tech_keywords: [
      "reit",
      "reits",
      "capital allocation",
      "funding",
      "financing",
      "property financing",
      "housing finance",
      "housing financing",
      "capital raise",
      "office",
      "retail",
      "residential",
      "industrial",
      "logistics",
      "leasing",
      "rent",
      "rents",
      "rental",
      "wfh",
      "return to office",
      "end-user",
      "buyer behavior",
      "supply",
      "demand",
      "market balance"
    ],
    applied_human_keywords: [
      "pressure",
      "strain",
      "mismatch",
      "slowdown",
      "slower",
      "weaker",
      "shift",
      "shifting",
      "uneven",
      "overhang",
      "risk",
      "tightening",
      "easing",
      "repricing"
    ],
    keep_signal_keywords: {
      model_release: [
        "price movement",
        "price pressure",
        "affordability",
        "purchasing power",
        "rent",
        "rents",
        "rental",
        "take-up",
        "take up",
        "occupancy",
        "vacancy"
      ],
      developer_platform: [
        "housing loan",
        "housing loans",
        "housing lending",
        "housing credit",
        "home financing",
        "green home financing",
        "green housing lending",
        "home loan",
        "home loans",
        "mortgage",
        "mortgages",
        "mortgage lending",
        "real estate lending",
        "residential real estate lending",
        "property financing",
        "financing",
        "bank lending",
        "capital charge",
        "capital requirement",
        "interest rate",
        "interest rates"
      ],
      ai_infrastructure: [
        "construction",
        "building permits",
        "pipeline",
        "inventory",
        "supply",
        "unsold inventory",
        "oversupply",
        "project delays"
      ],
      enterprise_rollout: [
        "office demand",
        "leasing",
        "occupancy",
        "vacancy",
        "retail traffic",
        "industrial demand",
        "logistics demand",
        "return to office",
        "wfh"
      ],
      strategic_partnership: [
        "reit",
        "reits",
        "capital allocation",
        "funding",
        "capital raise",
        "joint venture",
        "foreign investment"
      ],
      policy_regulation: [
        "bsp",
        "bangko sentral",
        "dhsud",
        "neda",
        "dof",
        "policy",
        "regulation",
        "capital charge",
        "capital charges",
        "capital requirement",
        "capital requirements",
        "lending rule",
        "lending rules",
        "risk weight",
        "risk weights",
        "zoning",
        "land use",
        "tax",
        "incentive"
      ],
      licensing_copyright: [
        "permits",
        "building permits",
        "license",
        "compliance",
        "zoning",
        "land use"
      ],
      safety_governance: [
        "stress",
        "distress",
        "defaults",
        "delays",
        "vacancy",
        "oversupply",
        "weak demand",
        "weaker demand"
      ],
      strategic_finance: [
        "reit",
        "bond",
        "notes",
        "funding",
        "financing",
        "property financing",
        "housing finance",
        "housing financing",
        "capital raise",
        "debt",
        "loan",
        "home loan",
        "housing loan",
        "mortgage"
      ]
    },
    junk_keywords: [
      "luxury living",
      "dream home",
      "best places to invest",
      "where to invest",
      "amenities",
      "amenity",
      "award",
      "awards",
      "recognition",
      "ribbon-cutting",
      "groundbreaking ceremony",
      "grand launch",
      "celebrity home",
      "house tour",
      "interior design",
      "home decor",
      "open house",
      "promo",
      "discount",
      "reservation fee"
    ],
    min_score: 5
  }
};
