import type { Beat } from "../lib/types.js";

export type BeatRelevanceConfig = {
  core_ai_keywords: string[];
  ai_infra_keywords: string[];
  adjacent_tech_keywords: string[];
  applied_human_keywords: string[];
  keep_signal_keywords: {
    model_release: string[];
    developer_platform: string[];
    ai_infrastructure: string[];
    enterprise_rollout: string[];
    strategic_partnership: string[];
    policy_regulation: string[];
    licensing_copyright: string[];
    safety_governance: string[];
    strategic_finance: string[];
  };
  junk_keywords: string[];
  min_score: number;
};

export const relevanceConfigByBeat: Record<Beat, BeatRelevanceConfig> = {
  ai_tech: {
    core_ai_keywords: [
      "ai",
      "artificial intelligence",
      "machine learning",
      "generative ai",
      "genai",
      "model",
      "models",
      "llm",
      "llms",
      "large language model",
      "large language models",
      "language model",
      "language models",
      "gpt",
      "dall-e",
      "dalle",
      "clip",
      "whisper",
      "codex",
      "operator",
      "system card",
      "reasoning",
      "alignment",
      "benchmark",
      "eval",
      "evaluation",
      "model spec",
      "vision",
      "sora",
      "multimodal",
      "inference",
      "training",
      "fine-tuning",
      "fine tuning",
      "image generation",
      "text to image",
      "theorem proving",
      "reinforcement learning",
      "rl",
      "robotics",
      "embeddings",
      "curriculum learning",
      "neural network",
      "neural networks",
      "transformer",
      "transformers",
      "diffusion",
      "prompt injection",
      "policy gradient",
      "math word problems",
      "prompt",
      "prompts",
      "use case",
      "use-case",
      "business",
      "enterprise",
      "workflow",
      "productivity",
      "application",
      "applications",
      "customer service",
      "developer",
      "developers",
      "reasoning model",
      "agent",
      "agents",
      "agentic",
      "openai",
      "anthropic",
      "claude",
      "chatgpt",
      "gemini",
      "copilot"
    ],
    ai_infra_keywords: [
      "gpu",
      "gpus",
      "chip",
      "chips",
      "semiconductor",
      "cuda",
      "tpu",
      "inference chip",
      "data center",
      "datacenter",
      "cloud",
      "compute",
      "accelerator",
      "accelerated computing",
      "foundation model",
      "model serving",
      "ai factory",
      "robotics",
      "autonomous",
      "developer platform",
      "api",
      "infrastructure"
    ],
    adjacent_tech_keywords: [
      "antitrust",
      "regulation",
      "policy",
      "copyright",
      "safety",
      "security",
      "cybersecurity",
      "privacy",
      "platform",
      "app store",
      "search",
      "browser",
      "microsoft",
      "google",
      "meta",
      "amazon",
      "apple",
      "nvidia",
      "startup",
      "business software",
      "enterprise ai",
      "enterprise workflow",
      "developer tools",
      "enterprise software",
      "developer",
      "open source"
    ],
    applied_human_keywords: [
      "how to",
      "ways to",
      "using ai",
      "use ai",
      "everyday",
      "daily",
      "workflow",
      "automate",
      "automation",
      "productivity",
      "save time",
      "real world",
      "real-world",
      "small business",
      "freelancer",
      "student",
      "teacher",
      "marketing",
      "sales",
      "content",
      "customer service",
      "operations",
      "hiring",
      "training",
      "fun",
      "weird",
      "viral",
      "trend",
      "experiment",
      "challenge",
      "test",
      "people are using",
      "someone used ai to",
      "created using ai",
      "generated using ai",
      "understanding",
      "impact",
      "ethical"
    ],
    keep_signal_keywords: {
      model_release: [
        "introducing",
        "launch",
        "launches",
        "released",
        "release",
        "update",
        "now available",
        "system card",
        "model spec"
      ],
      developer_platform: [
        "api",
        "developer",
        "developers",
        "developer platform",
        "sdk",
        "platform",
        "devtools",
        "app server"
      ],
      ai_infrastructure: [
        "gpu",
        "chip",
        "chips",
        "compute",
        "cloud",
        "data center",
        "datacenter",
        "inference",
        "training",
        "semiconductor",
        "infrastructure"
      ],
      enterprise_rollout: [
        "deploy",
        "deployment",
        "rollout",
        "scale",
        "scaling",
        "enterprise",
        "for work",
        "business",
        "workforce"
      ],
      strategic_partnership: [
        "partner",
        "partners",
        "partnership",
        "collaborate",
        "collaboration",
        "joint statement",
        "agreement"
      ],
      policy_regulation: [
        "policy",
        "regulation",
        "regulatory",
        "court",
        "lawsuit",
        "litigation",
        "antitrust",
        "doj",
        "eu"
      ],
      licensing_copyright: [
        "license",
        "licenses",
        "licensing",
        "copyright",
        "publisher",
        "publishers",
        "news organizations",
        "content partnership"
      ],
      safety_governance: [
        "safety",
        "governance",
        "alignment",
        "risk",
        "trust",
        "security",
        "evaluation",
        "eval",
        "red team"
      ],
      strategic_finance: [
        "funding",
        "fundraise",
        "investment",
        "invests",
        "stake",
        "acquire",
        "acquisition",
        "credit facility"
      ]
    },
    junk_keywords: [
      "coupon",
      "promo code",
      "coupons",
      "deals",
      "discount",
      "sale",
      "price drop",
      "under $",
      "percent off",
      "off right now",
      "for the rest of today",
      "roundup",
      "gift guide",
      "buy now",
      "where to buy",
      "earbuds",
      "phone case",
      "apple watch bands",
      "outdoor pizza ovens",
      "accessories",
      "geforce now",
      "cloud gaming",
      "game on"
    ],
    min_score: 2
  }
};
